FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app
EXPOSE 502 102 20000 2404 4840 44818
CMD ["python","-m","icsforge.receiver.receiver","--config","icsforge/receiver/config.yml","--bind","0.0.0.0"]
